name: Eight Workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom: 
        description: Type the title
        type: string
        required: true
        default: "Hello World"
      selectCustom:
        description: Select value
        type: choice
        required: true
        options:
          - catFirst
          - catSecond
          - catThird
        default: catSecond
      checkCustom:
        description: Check box box
        type: boolean
        required: false

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event variables
        run: |
          echo "Title: ${{inputs.titleCustom}}" 
          echo "Selected: ${{inputs.selectCustom}}"
          echo "Checked: ${{inputs.checkCustom}}"

#  send post request with:
#  link: https://api.github.com/repos/snjk333/studyGitHub_Actions/actions/workflows/eight_workflow.yml/dispatches
# json:
# {
#     "ref": "main",
#     "inputs":{
#         "titleCustom": "hello from postman",
#         "selectCustom": "catThird"
#     }
# }
# Add headers from github documentation
# https://docs.github.com/ru/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event