name: Fifth Workflow

on: [push, issues, pull_request]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event variables
        run: |
          echo $GITHUB_SHA 
          echo $GITHUB_REF
        # commit id and commit branch
          