name: Fourth Workflow

on: 
    workflow_run:
        workflows: ["Third Workflow"]
        types:
          - completed
jobs:
  success-command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: say after third workflow success
        run: echo "Success"
  failure-command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - name: say after third workflow failure
        run: echo "Failure"