name: Fourth Workflow

on: 
    workflow_run:
        workflows: ["Third Workflow"]
        types:
          - completed
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: say hello after third workflow completion
        run: echo "hello"