name: Third Workflow

on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -la
        
      - uses: actions/checkout@v6
      
      - name: List files after checkout
        run: ls -la