name: Third Workflow

on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: |
          ls -la
        #  lslsls -a

      #- uses: actions/checkout@v6
      # OR with git commands

      - name: copy files like checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main


      - name: List files after checkout
        run: ls -la